#!/bin/bash

readonly DIR_SEP="_"
readonly DIR_SEP2="."



sravnenie(){

#create massivs
array_v=(${1//${DIR_SEP}/ })
array_v_max=(${2//${DIR_SEP2}/ })
array_v=(${array_v[1]//${DIR_SEP2}/ })


#test_empty
for ((j=0; j<4; j++)) do

if [ "x${array_v[$j]}" = "x" ]; then
array_v[$j]=0
fi

if [ "x${array_v_max[$j]}" = "x" ]; then
array_v_max[$j]=0
fi


done


#echo "$v_str ${array_v[2]} ${array_v_max[0]}"

#analiz
if (( ${array_v_max[0]}>${array_v[0]} )); then
    echo "rm -rf $3/$1"
    else
      if (( ${array_v_max[0]}==${array_v[0]} )); then
         if (( ${array_v_max[1]}>${array_v[1]} )); then
            echo "rm -rf $3/$1"
            else
            if (( ${array_v_max[1]}==${array_v[1]} )); then 
                if (( ${array_v_max[2]}>${array_v[2]} )); then
                   echo "rm -rf $3/$1"
                   else
                   if (( ${array_v_max[2]}==${array_v[2]} )); then
                       if (( ${array_v_max[3]}>${array_v[3]} )); then
                          echo "rm -rf $3/$1"
                           
    
fi
fi
fi
fi
fi
fi
fi

}

#create massiv dir
FILES=(`ls -d $1/*/ | tr -d /$1`)
patch=$1

#read massiv
for ((i=0; i<${#FILES[@]}; i++))
do

#print massiv
echo ${FILES[$i]}

sravnenie ${FILES[$i]} $2 $patch
done
